### ISSUE TITLE
Provide a method for checking if secret is valid to avoid panic checking

### ISSUE THREAD

**Issue by djherbis** [xlzd/gotp#18]
Calls time Now() and At() can panic if the secret is invalid, but there's no safe way using this library to check if the secret is valid without handling the panic.

Providing a non-panic method for checking this would be ideal (IsValid() or something which could return the err from byteSecret() instead of panicing).

Most APIs should not panic and should just push errors up the stack instead.

**Comment by mergenchik** [comment]
good point @djherbis, if anybody has time to implement it and send PR, I will review this.

**Comment by mergenchik** [comment]
Closing this issue, implemented in #24
