### ISSUE TITLE
'@' Symbol

### ISSUE THREAD

**Issue by rhysjtevans** [xlzd/gotp#21]
https://github.com/xlzd/gotp/blob/fab697c03c2c75f423710795f6b00b53c6c5442f/utils.go#L42

Hi, I've stumbled on your library and like it! While I was testing I noticed this.
Most accounts are linked to email addresses that obviously include '@' symbol.
Any reason why we are URL Escaping the account?

Problem is when passing the URI to a QR code generator the email is translated to `....%40domain.com`

**Comment by rhysjtevans** [comment]
Temporarily getting round this via a text replace on the string before passing it to the QR Code generator but would be nice if you removed this

**Comment by mergenchik** [comment]
Hi, in official [docs](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) label should be **URI** encoded, but not **URL**.

**Comment by mergenchik** [comment]
@rhysjtevans can you please check and confirm that current issue is fixed

**Comment by mergenchik** [comment]
Closing this issue
