### ISSUE TITLE
totp.go times other than now

### ISSUE THREAD

**Issue by Dr-Syn** [xlzd/gotp#6]
Good afternoon;

In the totp.go function "At" you've got an 'int' timestamp - presumably a UNIX time integer - being fed into that function.

Seeing as you've already got "time" as a dependency, perhaps it might be better for that to be a "Time" object? This way, users of the library can have the Time functions calculate the various windows and such rather than having to extract the current or future time, do the conversion, and then convert to an int to feed into that function.

I already have to call https://golang.org/pkg/time/#Unix to get that, after all

**Comment by mergenchik** [comment]
Yes, actually we can add extra method which will accept Time struct as parameter.

**Comment by mergenchik** [comment]
Maybe also solve #10 by adding extra method.

**Comment by mergenchik** [comment]
Closing this issue, implemented in #24

**Comment by Dr-Syn** [comment]
Oh awesome; thank you!
