### ISSUE TITLE
How to set step length for TOTP?

### ISSUE THREAD

**Issue by jiftle** [xlzd/gotp#7]
TOTP algorithm has the param of control step length , but I don't found it. Please ...

```
// Generate the current time OTP and expiration time
func (t *TOTP) NowWithExpiration() (string, int64) {
	interval64 := int64(t.interval)
	timeCodeInt64 := time.Now().Unix() / interval64
	expirationTime := (timeCodeInt64 + 1) * interval64
	return t.generateOTP(int(timeCodeInt64)), expirationTime
}
```

**Comment by mergenchik** [comment]
@jiftle `t.interval` is step length.

You can use `NewTOTP(secret string, digits, interval int, hasher *Hasher) *TOTP` function, for other parameters refer to `NewDefaultTOTP(secret string)` for usage, both in `totp.go` file.

**Comment by mergenchik** [comment]
@jiftle can we close this issue now?
